//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipo
    {
        public string serie { get; set; }
        public string observaciones { get; set; }
        public int laboratorio_num_fk { get; set; }
        public string laboratorio_edificio_fk { get; set; }
        public string t_equipo_fk { get; set; }
        public string e_equipo_fk { get; set; }
    
        public virtual laboratorio laboratorio { get; set; }
        public virtual estado_equipo estado_equipo { get; set; }
        public virtual tipo_equipo tipo_equipo { get; set; }
    }
}
