//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elabs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class elabsEntities : DbContext
    {
        public elabsEntities()
            : base("name=elabsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<edificio> edificios { get; set; }
        public virtual DbSet<equipo> equipoes { get; set; }
        public virtual DbSet<estado> estadoes { get; set; }
        public virtual DbSet<estado_equipo> estado_equipo { get; set; }
        public virtual DbSet<laboratorio> laboratorios { get; set; }
        public virtual DbSet<reserva> reservas { get; set; }
        public virtual DbSet<tipo_equipo> tipo_equipo { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
