//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int identificador { get; set; }
        public int usuario_fk { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public int laboratorio_num_fk { get; set; }
        public string laboratorio_edificio_fk { get; set; }
    
        public virtual laboratorio laboratorio { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
